[package]
name = "dotrix"
version = "0.1.0"
authors = [
  "Elias Kartashov <elias@lowenware.com>",
  "Štěpán Wünsch <sw@lowenware.com>",
  "Nikita Zemtsov <z-nik@ya.ru>",
]
edition = "2018"
description = "3D Game Engine"
license = "MIT"

# [features]
# default = [
#     "my_feature",
# ]

[dependencies]
cgmath = "0.17"
futures = { version = "0.3", default-features = false, features = ["std"] }
png = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shaderc = "0.7"
strum = "0.19"
strum_macros = "0.19"
wgpu = "0.6"
wgpu-subscriber = "0.1.0"
winit = { version = "0.23.0", features = ["serde"] }
bytemuck = { version = "1.4", features = ["derive"] }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }

[[example]]
name = "demo"
path = "examples/demo/demo.rs"

#[[example]]
#name = "ecs"
#path = "examples/ecs.rs"
